let data=window.DARTS_DATA;const container=document.getElementById('matchesContainer'),summary=document.getElementById('summaryStrip');
function initials(n){return n.split(' ').map(p=>p[0]).slice(0,2).join('')}
function statusLabel(m){return m.status==='live'?'● Live':m.status==='final'?'Final':m.time}
function mean(a){const clean=(a||[]).filter(v=>Number.isFinite(Number(v))).map(Number);return clean.length?clean.reduce((s,v)=>s+v,0)/clean.length:null}
function last10(values){return (values||[]).filter(v=>Number.isFinite(Number(v))).map(Number).slice(-10)}
function yearValues(p,type){const keys=type==='checkout'?['checkout2026','yearCheckoutValues','seasonCheckout']:['form2026','yearAvgValues','seasonAverages'];for(const key of keys){if(Array.isArray(p[key])&&p[key].length)return p[key]}return null}
function playerRow(p,score,market,status){return `<div class="player-row"><div class="avatar portrait-placeholder"><span>${initials(p.name)}</span></div><div class="player-identity"><div class="player-name-line"><span class="player-name">${p.name}</span>${status!=='final'?`<span class="player-odds">${market||'—'}</span>`:''}</div><div class="player-meta"><span class="country-badge country-${p.country.toLowerCase()}"></span>${p.country} • ${p.avg.toFixed(1)} recent avg</div></div><div class="score">${score??''}</div></div>`}
function summaryBox(p,type){const vals=last10(type==='checkout'?p.checkout:p.form),suffix=type==='checkout'?'%':'',last10Mean=mean(vals),rawYear=yearValues(p,type),yearMean=rawYear?mean(rawYear):(type==='checkout'?(Number.isFinite(p.yearCheckout)?p.yearCheckout:null):(Number.isFinite(p.yearAvg)?p.yearAvg:null));const fmt=v=>v==null?'—':`${v.toFixed(2)}${suffix}`;return `<div class="trend-summary"><strong>${p.name}</strong><div><span>LAST 10 AVG <b>${fmt(last10Mean)}</b></span><span>2026 AVG <b>${fmt(yearMean)}</b></span></div></div>`}
function chartBlock(m,i,type,title,note){return `<div class="trend-panel compact-trend"><div class="trend-head"><div><span class="trend-kicker">10-MATCH TREND</span><h3>${title}</h3></div><span class="trend-note">${note}</span></div><div class="chart-wrap"><canvas id="${type}-${i}" width="700" height="230"></canvas></div><div class="chart-legend large-legend"><span><i class="series-dot series-one"></i>${m.player1.name}</span><span><i class="series-dot series-two"></i>${m.player2.name}</span></div><div class="trend-summary-grid">${summaryBox(m.player1,type)}${summaryBox(m.player2,type)}</div></div>`}
function chartMarkup(m,i){return `<div class="analytics-grid">${chartBlock(m,i,'avg','3-Dart Average','Oldest → newest')}${chartBlock(m,i,'checkout','Checkout Rate','Percent • oldest → newest')}</div>`}
function drawTrend(c,m,type){if(!c||c.dataset.drawn)return;const a=last10(type==='checkout'?m.player1.checkout:m.player1.form),b=last10(type==='checkout'?m.player2.checkout:m.player2.form);if(!a.length||!b.length)return;const ctx=c.getContext('2d'),d=window.devicePixelRatio||1,w=c.clientWidth,h=230;c.width=w*d;c.height=h*d;ctx.scale(d,d);c.dataset.drawn='true';const p={l:42,r:20,t:30,b:32},vals=[...a,...b],mn=type==='checkout'?Math.max(0,Math.floor(Math.min(...vals)-7)):Math.floor(Math.min(...vals)-4),mx=type==='checkout'?Math.min(100,Math.ceil(Math.max(...vals)+7)):Math.ceil(Math.max(...vals)+4),count=Math.max(a.length,b.length),x=i=>p.l+i*((w-p.l-p.r)/Math.max(1,count-1)),y=v=>p.t+(mx-v)*((h-p.t-p.b)/(mx-mn));ctx.font='10px Inter';ctx.fillStyle='#93a49f';ctx.strokeStyle='rgba(245,238,215,.10)';for(let i=0;i<4;i++){const v=mn+i*((mx-mn)/3),yy=y(v);ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke();ctx.fillText(`${v.toFixed(0)}${type==='checkout'?'%':''}`,5,yy+4)}for(let i=0;i<count;i++)ctx.fillText(String(i+1),x(i)-3,h-9);function series(s,col){ctx.strokeStyle=col;ctx.lineWidth=3;ctx.beginPath();s.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke();s.forEach((v,i)=>{const xx=x(i),yy=y(v);ctx.fillStyle=col;ctx.beginPath();ctx.arc(xx,yy,4,0,Math.PI*2);ctx.fill();const txt=`${v.toFixed(1)}${type==='checkout'?'%':''}`;ctx.font='700 10px Inter';const tw=ctx.measureText(txt).width;const boxH=14;ctx.fillStyle='rgba(5,13,10,.88)';ctx.fillRect(xx-tw/2-3,yy-boxH/2,tw+6,boxH);ctx.fillStyle=col;ctx.textBaseline='middle';ctx.fillText(txt,xx-tw/2,yy);ctx.textBaseline='alphabetic'})}series(a,'#e72a34');series(b,'#f2c94c')}
function currentKey(){return Object.keys(window.DARTS_DATES).find(k=>window.DARTS_DATES[k]===data)||'2026-09-30'}
function renderSummary(){const total=data.matches.length,live=data.matches.filter(m=>m.status==='live').length,tournaments=new Set(data.matches.map(m=>m.tournament)).size;summary.innerHTML=`<div class="summary-card date-card"><span>Date</span><select id="dateSelect" class="date-select"><option value="2026-09-29">Yesterday • Sep 29</option><option value="2026-09-30">Today • Sep 30</option><option value="2026-10-01">Tomorrow • Oct 1</option></select></div>${[['Matches',total],['Live now',live],['Tournaments',tournaments]].map(([l,v],i)=>`<div class="summary-card metric-card metric-${i+1}"><span>${l}</span><strong>${v}</strong></div>`).join('')}`;document.getElementById('dateSelect').value=currentKey();document.getElementById('dateSelect').addEventListener('change',e=>{data=window.DARTS_DATES[e.target.value];renderSummary();renderMatches();const h=document.getElementById('matchHeading');if(h)h.textContent=`${data.label}'s Matches`})}
function renderMatches(){const grouped=data.matches.reduce((a,m,i)=>{const k=`${m.tournament}__${m.round}`;if(!a[k])a[k]={tournament:m.tournament,round:m.round,matches:[]};a[k].matches.push({...m,chartIndex:i});return a},{});container.innerHTML=Object.values(grouped).map(g=>`<section class="tournament-block"><div class="tournament-head"><strong>${g.tournament}</strong><span>${g.round}</span></div>${g.matches.map(m=>`<article class="match-card visual-card" tabindex="0" data-chart="${m.chartIndex}"><div class="status ${m.status}">${statusLabel(m)}<small>${m.status==='upcoming'?'Upcoming':m.status==='live'?'In progress':''}</small></div><div class="players">${playerRow(m.player1,m.score1,m.market1,m.status)}<div class="versus">VS</div>${playerRow(m.player2,m.score2,m.market2,m.status)}</div><div class="open-arrow">›</div><div class="details">${chartMarkup(m,m.chartIndex)}</div></article>`).join('')}</section>`).join('');document.querySelectorAll('.match-card').forEach(card=>{const toggle=()=>{card.classList.toggle('open');if(card.classList.contains('open')){const i=Number(card.dataset.chart),m=data.matches[i];requestAnimationFrame(()=>{drawTrend(document.getElementById(`avg-${i}`),m,'avg');drawTrend(document.getElementById(`checkout-${i}`),m,'checkout')})}};card.addEventListener('click',toggle);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})})}
renderSummary();renderMatches();