const data=window.DARTS_DATA,container=document.getElementById('matchesContainer'),summary=document.getElementById('summaryStrip');
function initials(n){return n.split(' ').map(p=>p[0]).slice(0,2).join('')}
function statusLabel(m){return m.status==='live'?'Live':m.status==='final'?'Final':m.time}
function playerRow(p,score,odds,status){const market=status==='final'?'':`<div class="player-odds"><small>MONEYLINE</small><strong>${odds}</strong></div>`;return `<div class="player-row"><div class="avatar portrait-placeholder"><span>${initials(p.name)}</span></div><div class="player-identity"><div class="player-name">${p.name}</div><div class="player-meta"><span class="flag">${p.flag||''}</span>${p.country} • ${p.avg.toFixed(1)} recent avg</div></div>${market}<div class="score">${score??''}</div></div>`}
function formBox(p){return `<div class="form-box"><h4>${p.name} — last 5 averages</h4><div class="form-line">${p.form.map(v=>`<span class="pill">${v.toFixed(1)}</span>`).join('')}</div></div>`}
function chartMarkup(m,i){return `<div class="trend-panel"><div class="trend-head"><div><span class="trend-kicker">FORM TREND</span><h3>Recent 3-Dart Averages</h3></div><span class="trend-note">Most recent →</span></div><div class="chart-wrap"><canvas id="chart-${i}" width="900" height="260"></canvas></div><div class="chart-legend"><span><i class="series-dot series-one"></i>${m.player1.name}</span><span><i class="series-dot series-two"></i>${m.player2.name}</span></div></div>`}
function drawTrend(c,m){if(!c||c.dataset.drawn)return;const xctx=c.getContext('2d'),d=window.devicePixelRatio||1,w=c.clientWidth,h=260;c.width=w*d;c.height=h*d;xctx.scale(d,d);c.dataset.drawn='true';const p={l:44,r:18,t:22,b:35},vals=[...m.player1.form,...m.player2.form],mn=Math.floor(Math.min(...vals)-2),mx=Math.ceil(Math.max(...vals)+2),x=i=>p.l+i*((w-p.l-p.r)/4),y=v=>p.t+(mx-v)*((h-p.t-p.b)/(mx-mn));xctx.font='11px Inter';xctx.fillStyle='#9b9b8e';xctx.strokeStyle='rgba(239,230,199,.10)';for(let i=0;i<4;i++){const v=mn+i*((mx-mn)/3),yy=y(v);xctx.beginPath();xctx.moveTo(p.l,yy);xctx.lineTo(w-p.r,yy);xctx.stroke();xctx.fillText(v.toFixed(0),8,yy+4)}['-5','-4','-3','-2','-1'].forEach((l,i)=>xctx.fillText(l,x(i)-6,h-10));function series(s,col){xctx.strokeStyle=col;xctx.lineWidth=3;xctx.beginPath();s.forEach((v,i)=>i?xctx.lineTo(x(i),y(v)):xctx.moveTo(x(i),y(v)));xctx.stroke();s.forEach((v,i)=>{xctx.fillStyle=col;xctx.beginPath();xctx.arc(x(i),y(v),4.5,0,Math.PI*2);xctx.fill()})}series(m.player1.form,'#d72c32');series(m.player2.form,'#1f7a4c')}
function renderSummary(){const total=data.matches.length,live=data.matches.filter(m=>m.status==='live').length,tournaments=new Set(data.matches.map(m=>m.tournament)).size;summary.innerHTML=`<div class="summary-card date-card"><span>Date</span><select id="dateSelect" aria-label="Choose date"><option value="2026-09-29">September 29, 2026</option><option value="2026-09-30" selected>September 30, 2026</option><option value="2026-10-01">October 1, 2026</option></select><small id="dateHint">Today</small></div>`+[['Matches today',total],['Live now',live],['Tournaments',tournaments]].map(([l,v])=>`<div class="summary-card"><span>${l}</span><strong>${v}</strong></div>`).join('');document.getElementById('dateSelect').addEventListener('change',e=>{const hint=document.getElementById('dateHint'),v=e.target.value;hint.textContent=v==='2026-09-30'?'Today':v==='2026-09-29'?'Yesterday • schedule coming next':'Tomorrow • schedule coming next'})}
function renderMatches(){const grouped=data.matches.reduce((a,m,i)=>{const k=`${m.tournament}__${m.round}`;if(!a[k])a[k]={tournament:m.tournament,round:m.round,matches:[]};a[k].matches.push({...m,chartIndex:i});return a},{});container.innerHTML=Object.values(grouped).map(g=>`<section class="tournament-block"><div class="tournament-head"><strong>${g.tournament}</strong><span>${g.round}</span></div>${g.matches.map(m=>`<article class="match-card visual-card" tabindex="0" data-chart="${m.chartIndex}"><div class="status ${m.status}">${statusLabel(m)}<small>${m.status==='upcoming'?'Upcoming':''}</small></div><div class="players">${playerRow(m.player1,m.score1,m.market1,m.status)}<div class="versus">VS</div>${playerRow(m.player2,m.score2,m.market2,m.status)}</div><div class="open-arrow">›</div><div class="details">${chartMarkup(m,m.chartIndex)}<div class="form-grid">${formBox(m.player1)}${formBox(m.player2)}</div></div></article>`).join('')}</section>`).join('');document.querySelectorAll('.match-card').forEach(card=>{const toggle=()=>{card.classList.toggle('open');if(card.classList.contains('open')){const i=Number(card.dataset.chart);requestAnimationFrame(()=>drawTrend(document.getElementById(`chart-${i}`),data.matches[i]))}};card.addEventListener('click',toggle);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})})}
renderSummary();renderMatches();